OrdererOrgs:
  - Name: Orderer
    Domain: themenadesk.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
PeerOrgs:
  - Name: survey
    Domain: survey.themenadesk.com
    EnableNodeOUs: true
    Template:
        Count: 2
    Users:
        Count: 1