OrdererOrgs:
  - Name: Orderer
    Domain: livwell.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
PeerOrgs:
  - Name: allparticipants
    Domain: allparticipants.livwell.com
    EnableNodeOUs: true
    Template:
        Count: 2
    Users:
        Count: 1